language: node_js
cache:
  directories: 
    - ~!@/.npm
node_js:
  - '10.16.0'

git: 
  depth: 3
script:
  -yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GitHub_Token
  local-dir: dist/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: develop
